### PR TITLE
feat: herosec

### PR DESCRIPTION
**Pull request by ManikanthMartha**
# Description & Technical Solution

Describe problems, if any, clearly and concisely.
Summarize the impact to the system.
Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] Already rebased against main branch.

# Screenshots

Provide screenshots or videos of the changes made if any.

## Summary by CodeRabbit

- **New Features**
  - Introduced interactive `AceButton` and `HoverBorderGradient` components for enhanced user interaction.
  - Added a new `TextHighlight` function in the Hero section.

- **Enhancements**
  - Updated the `Hero` component with new buttons, dynamic rendering, and improved styling.
  - Improved navbar content and structure, including a new "Request Meeting" button.

- **Bug Fixes**
  - Adjusted class names and styles in `NavbarBlack` for better layout and consistency.

- **Style**
  - Enhanced CSS classes for scroll snapping, typography, and animations.

- **Dependencies**
  - Updated `framer-motion` to `10.18.0` and `tailwind-merge` to `1.14.0`.

- **Configuration**
  - Updated `tailwind.config.ts` to include new font definitions and plugins.
  - Simplified `tsconfig.json` for better readability.

### CODE REVIEW

**Comment by Crimson-Blade** [comment]
@coderabbitai review

**Comment by Crimson-Blade** [comment]
@coderabbitai review

**Comment by ManikanthMartha** [comment]
not so-necessary changes 
merge 🫶

**Comment by Crimson-Blade** [comment]
@ManikanthMartha lgtm good job, merge done

**Pull request merged**
